import Script from 'next/script'
import SplitType from 'split-type'
import { Howl, Howler } from 'howler'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Navbar from '/components/ui/Navbar'
import Clients from '/components/ui/Clients'
import CrlnGlitch from '/components/ui/CrlnGlitch'

import styles from '@/styles/Home.module.css'
import Typography from '@mui/material/Typography'
import Accordion from '@mui/material/Accordion'
import AccordionSummary from '@mui/material/AccordionSummary'
import AccordionDetails from '@mui/material/AccordionDetails'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import { useState, SyntheticEvent } from 'react'

export default function Home() {
  return (
    <>
      <Script src="https://unpkg.com/split-type"></Script>
      <Script src="script/slider.js"></Script>
      <Script src="script/fontSplit.js"></Script>

      <Head>
        <title>Next.js + Tailwind CSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.typekit.net/udg8rud.css"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Pacifico"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Climate+Crisis"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Barlow+Semi+Condensed"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Rampart+One"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Rubik+Iso"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Comic+Neue"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Comic+Neue"
        ></link>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Cinzel"
        ></link>
      </Head>
      <div className="relative flex flex-col">
        <div className="relative w-[100vw] h-[100%] bg-white flex flex-col items-center justify-center p-5 md:p-10">
          <Navbar />
          <div className="relative flex flex-row w-[100%] h-[80vh] border-x-2 border-b-2 border-black justify-center items-center">
            <CrlnGlitch />
          </div>
        </div>
        <div className="relative w-[100vw] h-[100%] bg-white flex flex-col items-center justify-center p-10">
          <div className="h-20 w-[100%] border-2 border-black flex items-center justify-center">
            <h2 className="font-degular font-regular text-2xl">
              Who's telling the better story now?
            </h2>
          </div>
          <div className="relative flex flex-row w-[100%]  border-x-2 border-b-2 border-black">
            <div className="h-[100%] w-20 min-w-20 border-r-2 border-black"></div>
            <div className="relative rightPart sliderContent h-[100%]">
              {/* List of clients */}
              <div className="flex flex-col items-center justify-center p-10 border-x-2 border-black">
                <div className="flex flex-row items-center justify-center">
                  {/* Client's logo */}

                  {/* Client's quote and CTA */}
                  <Clients />
                </div>
              </div>
            </div>
            <div className="h-[100%] w-20 min-w-20 border-l-2 border-black"></div>
          </div>
        </div>
      </div>
      <div></div>
    </>
  )
}
